<!DOCTYPE html>
<html lang="en">

<head>
  <title>Custom Promises</title>
</head>

<body>
  <script>

/*The Async Await API is built upon promises.  However, it does not require .then
statements and is less 'call-backy'.  Your first declare a function with the word
async typed in front of the function name.  You then list each Promise to be executed
preceeded by the word await into the body of the async function.  Each promise will run
in order one at time once the previous function resolves similar to how generators
operate.*/

  function breath(amount) {
    return new Promise((resolve, reject) => {
      if(amount < 500) {
        reject('That is too small of a value');
      }
      setTimeout(() => resolve(`Done for ${amount}ms`), amount);
    });
  };

/*Here a higher order function is used to .catch any errors.  Wes explained that
this is a great technique to use if each promise will throw the same type of error.
However, if each promise has a unique type of possible error then it may be better
to use a try & catch.*/

  function catchErrors(fn) {
    return function(...args) {
      return fn(...args).catch((err) => {
        console.error('Whoops!');
        console.error(err);
      })
    }
  };


/*In Wes's example below, the result of each breath() call is stored in a variable
so that it can be displayed in the console.*/
  // async function go(first,last) {
  //     console.log(`You are next ${first} ${last}!`);
  //     var res = await breath(3000);
  //     console.log(res);
  //     var res = await breath(2000);
  //     console.log(res);
  //     var res = await breath(500);
  //     console.log(res);
  //     var res = await breath(4000);
  //     console.log(res);
  //     var res = await breath(700);
  //     console.log(res);
  //     var res = await breath(5000);
  //     console.log(res);
  //     console.log('end');
  // };
  //
  // const wrap = catchErrors(go);



//My Example:

/*Customer provides their name and drink selection.  If they don't give their name
& drink selection then we can't fulfill their order as the promise will reject.*/
//   function cuppaJoe(name, drink) {
//     return new Promise((resolve, reject) => {
//       if(arguments.length > 1) {
//         return setTimeout(()=> resolve(`${name}, your ${drink} is ready at the bar.`), 3000);
//       }
//         reject('Sorry, but we will need more info to complete your order.');
//     })
//   };
//
// /*Customer order is captured in a variable and returned to the console.*/
//   async function coffeeTime() {
//     console.log('Coffee shop is open!');
//     var order = await cuppaJoe('Dave', 'iced coffee');
//     console.log(order);
//     var order = await cuppaJoe('Cynthia', 'chai latte');
//     console.log(order);
//     var order = await cuppaJoe('Adalyn', 'chocolate milk');
//     console.log(order);
//     var order = await cuppaJoe('Angus', 'earl gray tea');
//     console.log(order);
//     console.log('Coffee shop is now closed!');
//   };
//
//   coffeeTime();

//Another Example:

// function strike(seconds) {
//   return new Promise((resolve,reject) => {
//     if(seconds) {
//       return setTimeout(()=> {
//         resolve(`The lightning strike was approximately ${seconds} miles away.`);
//       }, (seconds * 1000));
//     }
//     reject('Please enter the number of seconds elapsed from the lightning flash to hearing thunder.');
//   });
//   };
//
// async function distance() {
//   var dist = await strike(3);
//   console.log(dist);
//   var dist = await strike(5);
//   console.log(dist);
//   var dist = await strike(2);
//   console.log(dist);
//   var dist = await strike(1);
//   console.log(dist);
//   var dist = await strike(4);
//   console.log(dist);
//   var dist = await strike(4);
//   console.log(dist);
// };
//
// distance();




//How about another example:

/*In this example, a try catch is used to catch the error and log it to the
console. */

function alarm(snooze) {
  return new Promise((resolve,reject) => {
    if(snooze >2) {
      return setTimeout(()=> {
        resolve(`You have snoozed an extra ${snooze} seconds.`);
      }, (snooze * 1000))};
        reject(`Snooze time must be greater than 2 seconds. You have entered ${snooze} seconds.`);
    });
  };

async function wakeUp() {
  try {
    var beep = await alarm(3);
    console.log(beep);
    var beep = await alarm(3);
    console.log(beep);
    var beep = await alarm(5);
    console.log(beep);
    var beep = await alarm(2);
    console.log(beep);
    var beep = await alarm(4);
    console.log(beep);
    var beep = await alarm(6);
    console.log(beep);
    var beep = await alarm(5);
    console.log(beep);
  }
  catch(err) {
    console.error(err);
  }
};

wakeUp();


  </script>
</body>

</html>
